### ISSUE TITLE
Support resigning to Adhoc

### ISSUE THREAD

**Issue by dgranahan** [bitrise-steplib/steps-resign-ipa#8]
Resign-IPA step currently supports Appstore, InHouse, and Development. It looks like there are some subtle differences between InHouse and Adhoc (http://stackoverflow.com/questions/14858266/what-is-the-difference-between-in-house-versus-ad-hoc-distribution-for-enterpris). Could resign-IPA support Adhoc as well?

**Comment by viktorbenei** [comment]
I agree, it's not exactly clear - @godrei can you please check this?

I think what's called InHouse in this step is actually the "enterprise" dist. type

**Comment by godrei** [comment]
Hi @dgranahan sorry for my late response!

Could you please try to use `Export iOS and tvOS Xcode archive` step instead of this one?
Export archive uses `xcodebuild` build tool to export an .ipa file from .xcarchive, this is the recommended way to generate .ipa file.

If you are using `Xcode Archive for iOS` step to generate your first ipa file, just set `Export the generated archive?` input to `yes`, this case the step will export the generated xcarchive, into `BITRISE_XCARCHIVE_PATH` env var, which is the default value of `Export iOS and tvOS Xcode archive` step's `iOS or tvOS archive path` input.

**Comment by godrei** [comment]
Closing as we did not receive a reply - @dgranahan please let us know if we can help with anything and we'll reopen this issue!
